### ISSUE TITLE
Error: s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by partydiktator** [andyboeh/mediola2mqtt#15]
I recently did a fresh install of the HASS add-on. Ever since i'm getting the error _s6-overlay-suexec: fatal: can only run as pid 1_ when starting the add-on. This might be related to this update: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by andyboeh** [comment]
See #12.
