### ISSUE TITLE
Getting Keyerror

### ISSUE THREAD

**Issue by partydiktator** [andyboeh/mediola2mqtt#2]
Hi,

thanks for your work. When i'm starting the addon, i'm getting the following error:

![image](https://user-images.githubusercontent.com/20315883/119100441-3c627900-ba18-11eb-9f87-fa381f155935.png)

My config looks like this:

![image](https://user-images.githubusercontent.com/20315883/119100767-97946b80-ba18-11eb-84dc-fdaf15d26bee.png)

I'd appreciate any help.

Thanks, Oliver

**Comment by andyboeh** [comment]
Yes, that's a bug / a documentation problem. The intention was to move all configuration in add-on mode to the add-on configuration, that was partially provided by #1. 
I will look into it this weekend, I need to extend it to support multiple gateways anyway.

**Comment by andyboeh** [comment]
I just pushed a possible fix. Could you try the latest code? All configuration is now done directly within the add-on configuration, you do not need mediola2mqtt.yaml anymore! Personally, I cannot test it in add-on mode, as I run it as a  systemd service on my system.

**Comment by partydiktator** [comment]
I'm getting exactly the same error. Also, i can't configure in the add-on section:

![image](https://user-images.githubusercontent.com/20315883/119126757-b7855880-ba33-11eb-8755-8d3945f559da.png)

I'm very new to homeassistant so i might do something wrong here, but i deleted every add-on file and replaced them with your latest code. Also restartet server and all the noob stuff ...

**Comment by andyboeh** [comment]
I just pushed another fix. Did you rebuild the add-on? You need to do this after changing any of the add-on files.
I installed Hass.IO in a VM and installed the add-on. For me, the following configuration seems to work (my VM does not have access to my actual Mediola, so only limited tests were performed):

![Untitled](https://user-images.githubusercontent.com/3099753/119132407-efdc6500-ba3a-11eb-9326-0d7a90d8ec0b.png)

**Comment by partydiktator** [comment]
Finally i get the config within the add-on. However, when starting the add-on i'm getting the error "Missing option 'port' in mediola in Mediola to MQTT (local_mediola2mqtt)."

My config is:

mediola:
  host: 192.168.6.70
  udp_port: 1902
mqtt:
  host: 192.168.6.233
  port: 1803
  username: mqtt-user
  password: secret
  discovery_prefix: homeassistant
  topic: mediola
  debug: false
blinds:
  - type: ER
    adr: '01'
    name: Mediola Blind

**Comment by andyboeh** [comment]
Then you did not update again, that was a bug that I fixed an hour ago. Only config.json has changed.

**Comment by partydiktator** [comment]
No, i'm using the latest config.json. The moment i'm changing the tab from Configuration to Info to start the add-on, the config gets lost (resets to default) and yes, i hit the save button but it doesnt seem to work

**Comment by partydiktator** [comment]
Might be an issue with file permissions as I copied your code via scp as root.  Going to look into this later.

**Comment by andyboeh** [comment]
> No, i'm using the latest config.json. The moment i'm changing the tab from Configuration to Info to start the add-on, the config gets lost (resets to default) and yes, i hit the save button but it doesnt seem to work

I had the same problem and it worked for me after rebuilding the add-on.

> Might be an issue with file permissions as I copied your code via scp as root. Going to look into this later.

I did the same.

**Comment by partydiktator** [comment]
Now i did another rebuild and its working (at least i have a connection to the mediola blinds - i'm not able to control them at the moment, but might be my mistake. I think the save button "didn't work" because i had syntax errors in the config.

**Comment by partydiktator** [comment]
Just a short update why i wasn't able to control my blinds: i had a passwort set on my mediola gateway. In this case, the http requests require the password using the XC_PASS parameter: 

http://192.168.6.170/command?XC_PASS=password&XC_FNC=GetStates

I deactived the password on the gateway and now everything is fine.

**Comment by andyboeh** [comment]
Ah, thanks for the info - I didn't think about the password. Adding support for that should be rather trivial.

**Comment by andyboeh** [comment]
It should now also work with password-protected Mediolas - untested.
Btw, which Mediola do you have, i.e. v4 or a later version?

**Comment by partydiktator** [comment]
I'm using a v6 gateway
