### ISSUE TITLE
Install Addon to Homeassistant

### ISSUE THREAD

**Issue by jastBytes** [andyboeh/mediola2mqtt#22]
Hi! Thanks for the thing! But I am too stupid to get this addon installed into my Homeassistant. Is there a newer how-to? I don't know where the addon folder should be placed. I have the dockerized version running. Thank you!

**Comment by andyboeh** [comment]
Installing it as an add-on is unsupported from my side as I have no way to test or verify it. I will add a note about this to the README.

**Comment by andyboeh** [comment]
Which dockerized version do you mean, of Home Assistant? If yes, then you need to run mediola2mqtt natively on your docker host (or inside a separate docker container). Add-Ons only work for Home Assistant Operating System installations!

**Comment by jastBytes** [comment]
I managed to install it as an home assistant addon via my own repo https://github.com/jastBytes/hass-addons. So the addon is there, but I am now struggeling to control the elero blinds with the Mediola Gateway itself. ;-) So this is done basically.

**Comment by andyboeh** [comment]
OK, so you created your own add-on repository - good idea, that was missing anyway. As mentioned, however, I cannot support something I can't test and therefore I do not provide an add-on repository.

**Comment by rorso** [comment]
If I understand the "add-on" process correctly, the new repository is essentially a single file with some lines that only specify the name of the "add-on" and the URL where to fetch it. This URL points to [https://github.com/andyboeh/mediola2mqtt](https://github.com/andyboeh/mediola2mqtt). The file just marks it as HASS add-on when searched via "Community add-ons" plugin.

The code itself is fetched from your repository by the HA-OS with your readme and all current changes. As soon as you check in any changes, installations that fetched mediola2mqtt mediated by the "repository.yaml" from @jastBytes get notified that there is a new version available. Best of both worlds.

I know for sure that the module itself is running happily as add-on on the HA-OS, as It's how I have it running.

> but I am now struggeling to control the elero blinds with the Mediola Gateway itself. ;-)

Yes, the ELERO blinds are a bit picky. I too had to fiddle around quite a while till I got it running with MY remotes. Depending on the receiver, up/on/open may mean different things or you might need a "long press" or "double tap" instead. The API is very low level and agnostic to the controlled device.

The mediola2mqtt middleware therefore must do some mapping between the high level commands published to MQTT (by HA or others) and the low level API command that are required to get that done on YOUR devices.

I currently have some pull requests in review that should allow for a finer graded configuration of different command requirements without the need to rework the code.

**Comment by jastBytes** [comment]
I am using a v5 Gateway. Maybe that's the wrong one in combination with my blinds. I managed to control some Gira lights with the Gateway using IQONTROL. Now I did not find out yet how I get these into Home Assistant now.

**Comment by jastBytes** [comment]
It looks like the Gateway doesn't store the configured Gira lamps but the app on my phone. 🤔

**Comment by andyboeh** [comment]
You need to pair your Elero blinds to the Mediola gateway, the gateway then acts like a remote. You can use IQONTROL for this or the provided `mediolaManager.py` in this repository - keep in mind that I only tested the manager with the v4 gateway.

Your Elero motors need to be the newer bidirectional ones - the Mediola doesn't work with the unidirectional protocol.
