### ISSUE TITLE
How to install on HA Supervised please?

### ISSUE THREAD

**Issue by MirandaPoth** [andyboeh/mediola2mqtt#9]
Hi, 
I am very pleased to find this add-on! I was just about to try to develop my own code for controlling my Internorm blinds, which also use the Mediola gateway.

However I run HA Supervised, and when I try to add https://github.com/andyboeh/mediola2mqtt as an add-on repository it says 'Invalid Add-on repository!'. 

What am I doing wrong?

**Comment by andyboeh** [comment]
Nothing, it's not available as an add-on repository. You have to install it manually, see section "Installation" in the README.
